# Generated by Django 5.1 on 2024-08-29 14:08

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, max_length=100, null=True, verbose_name='Место выполнения')),
                ('time', models.DateTimeField(verbose_name="Время выполнения начала выполнения 'YYYY-MM-DD HH:MM'")),
                ('action', models.CharField(blank=True, max_length=100, null=True, verbose_name='Действие')),
                ('habit_is_pleasant', models.BooleanField(verbose_name='Признак приятной привычки')),
                ('number_of_executions', models.IntegerField(choices=[(1, 'один день'), (2, 'два дня'), (3, 'три дня'), (4, 'четыре дня'), (5, 'пять дней'), (6, 'шесть дней'), (7, 'семь дней')], default=1, verbose_name='Следующее выполнение через __ дней')),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=120), verbose_name='Продолжительность выполнения (в сукундах)')),
                ('is_published', models.BooleanField(default=True, verbose_name='Признак публичности')),
                ('reward', models.CharField(blank=True, max_length=100, null=True, verbose_name='Вознаграждение')),
                ('connection_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='habit_connect', to='habit.habit', verbose_name='Связанная привычка')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
                'ordering': ['time'],
            },
        ),
    ]
